name: elliptic_text
description: "Includes the EllipticText widget that lets you draw curved text.
 It comes with all the bells and whistles and is very easy to use."
repository: https://github.com/robmllze/elliptic_text
version: 1.0.1+7
environment:
  sdk: ">=2.13.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
